### ISSUE TITLE
Sessions are unset occasionally

### ISSUE THREAD

**Issue by LightningKat** [PEMapModder/LegionPE-Public-Resources#15] opened 2015-02-24 21:47 UTC
Everytime someone joins in spleef i cant talk why?

**Comment by PEMapModder** [comment] 2015-02-25 03:55
Can you make sure if it is when someone joins, a match ends, or what?

**Comment by LightningKat** [comment] 2015-02-25 10:06
I mean when sometimes won at spleef. Sorry

**Comment by LightningKat** [comment] 2015-02-25 10:07
When someone won in the spleef i cant talk.. And i need to relog

**Comment by LightningKat** [comment] 2015-02-25 10:07
To talk

**Comment by PEMapModder** [comment] 2015-02-25 11:17
Seems to be fixed. Tell me if this issue still exists.

**Comment by caingaroo** [comment] 2015-02-26 03:29
PEMapModder Can i be a tester for the SPLEEF on your server , and one of the mods banned me and it seid banned ip 60 days and i didnt do anything roung i didnt cuss didnt use mods i just played normal 
And my ign is XxCAINxX

**Comment by PEMapModder** [comment] 2015-02-26 04:14
@caingaroo this place is not for support.

**Comment by Zuppermaan** [comment] 2015-02-26 09:06
Whenever i win,i cant talk and need to relog,after some time (i.e. 10minutes) i loose the amount of wins and coins i have,please help

**Comment by Zuppermaan** [comment] 2015-02-26 09:09
Whenever i win,i cant talk and need to relog,after some time (i.e. 10minutes) i loose the amount of wins and coins i have,please help

**Comment by PEMapModder** [comment] 2015-02-26 10:36
Are you sure "after some time", not immediate?

**Comment by Zuppermaan** [comment] 2015-02-26 10:47
Just found out,Yes it is immediate.Hopefully that puts off another bug.i forgot it was immediate but now i remeber.

**Comment by PEMapModder** [comment] 2015-02-26 11:52
Please find other testers and try to find out who the buf is specific to, like, would it affect players who didn't join the tournament? What about players who have already lost? Etc.

**Comment by LightningKat** [comment] 2015-02-26 13:00
So is it fixed or nah?

**Comment by PEMapModder** [comment] 2015-02-26 13:40
Not yet

**Comment by Zuppermaan** [comment] 2015-02-26 20:21
No,it doesent affect those who arent in the match,only those who are and who won.

**Comment by Zuppermaan** [comment] 2015-02-26 20:22
And itonly happened to me at that time because i was the only one with a win

**Comment by PEMapModder** [comment] 2015-02-27 03:25
@Zuppermaan is it only for the last one who lost and the winner? Or the winner only?

**Comment by PEMapModder** [comment] 2015-02-27 03:26
Sorry I always clicked the closed it >_<

**Comment by Zuppermaan** [comment] 2015-02-27 05:26
Well,it happened to me immediately after i won and relogged,so yeah :/,btw will i be getting a reward for this?

**Comment by PEMapModder** [comment] 2015-02-27 05:32
@Zuppermaan I know, I want to ask if it is only you, or who else?

Say:

* Alice joined match
* Bob joined match
* Countdown started
* Cindy joined match
* David joined match
* Bob left the match
* Elvin joined the match
* Match started
* Alice quitted the server
* Cindy fell
* David fell
* Elvin won

Now, who can't chat?

What if David and Elvin both won (both didn't fall), who can't chat?

I hope you testers can reproduce this situation and find out who can't chat.

**Comment by Zuppermaan** [comment] 2015-02-27 09:07
Well something similar happened,im not sure if the loosers had to relog,but I did, im pretty sure if they both won both of them would need to log out and relog,thus making them loose the coins and points. Hope this helped.

**Closed** 2015-03-30 17:07 UTC
Labels: bug, Spleef
